---
- name: Install tzdata for Debian based distros
  apt:
    name: "{{ timezone_package }}"
    update_cache: true
    cache_valid_time: 86400
    state: present
  when: ansible_os_family == 'Debian'
  tags: ['timezone']
  become: true

- name: Set timezone config
  template:
    src: "timezone-{{ ansible_os_family }}.j2"
    dest: "{{ timezone_file }}"
  tags: ['timezone']
  become: true

- name: Set link to localtime
  file:
    state: link
    src: "{{ zoneinfo_dir }}{{ timezone }}"
    dest: "{{ localtime_file }}"
    force: true
  tags: ['timezone']
  become: true