- name: config | Configuring config.cfg
  template:
    src: etc/cloud/cloud.cfg.j2
    dest: /etc/cloud/cloud.cfg
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  when: cloud_init_configure