# tasks
- name: include platform vars
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"
- include: config.yml